server:
  port: 8084

spring:
  application:
    name: notification-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  mail:
    host: smtp.gmail.com
    port: 587
    username: myemailaddress@gmail.com
    password: aigv aacf ihud uqnm   # 16-character Google App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

